#!/bin/sh

# Script to copy the dot files.
# Written by Arun

mv ${HOME}/.bashrc    ${HOME}/.bashrc1
mv ${HOME}/.gitconfig ${HOME}/.gitconfig1
mv ${HOME}/.nanorc    ${HOME}/.nanorc1
mv ${HOME}/.nano      ${HOME}/.nano1

cp .bashrc    ${HOME}/
cp .gitconfig ${HOME}/
cp .nanorc    ${HOME}/
cp -r .nano   ${HOME}/

cp bin/createbackup        /usr/bin
cp etc/exclude-from-backup /etc/
