#!/bin/sh

# Script to copy the dot files.
# Written by Arun

mv ${HOME}/.bashrc    ${HOME}/.bashrc1
mv ${HOME}/.gitconfig ${HOME}/.gitconfig1
mv ${HOME}/.nanorc    ${HOME}/.nanorc1
mv ${HOME}/.nano      ${HOME}/.nano1

cp dotbashrc    ${HOME}/.bashrc
cp dotgitconfig ${HOME}/.gitconfig
cp dotnanorc    ${HOME}/.nanorc
cp -r dotnano   ${HOME}/.nano

cp bin/createbackup        /usr/bin
cp etc/exclude-from-backup /etc/
